import {CONFIG} from '../data/config.js';import {BUILDINGS} from '../data/buildings.js';import {SEASONS} from '../data/seasons.js';import {RESEARCH} from '../data/research.js';import {MAP} from '../data/map.js';
export class Game{
constructor(root){this.root=root;this.nodes=structuredClone(MAP.nodes);this.routes=MAP.routes;this.selected=null;this.armies=[];this.elapsed=0;this.seasonIndex=0;this.lastAI=0;this.mods={farmCapacity:0,mineCapacity:0,farmRate:1,mineRate:1,castleRate:1,academyRate:1,defense:1,travel:1,foodUse:1};this.food=20;this.gold=8;this.knowledge=0;this.logs=[];this.paused=false;this.gameOver=false;}
start(){this.renderShell();this.log('Bastion gestartet. Erobere die rote Burg.');this.render();this.timer=setInterval(()=>this.tick(CONFIG.tickMs/1000),CONFIG.tickMs);}
renderShell(){this.root.innerHTML=`<div class="app"><header class="top"><span class="brand">BASTION · Stage 1</span><span class="stat">🌾 <b id="food"></b></span><span class="stat">⛏️ <b id="gold"></b></span><span class="stat">🎓 <b id="knowledge"></b></span><span class="stat season" id="season"></span><button id="pause">Pause</button><button id="save">Speichern</button><button id="load">Laden</button></header><main class="main"><section class="map" id="map"></section><aside class="panel"><h2>Steuerung</h2><p>Klicke zuerst eine eigene Burg und danach ein Ziel an. Mit 25 %, 50 % oder 75 % schickst du Soldaten.</p><div class="actions"><button data-send=".25">25 % senden</button><button data-send=".5" class="primary">50 % senden</button><button data-send=".75">75 % senden</button><button id="upgrade">Ausgewähltes Gebäude upgraden (15 Gold)</button></div><h2>Logbuch</h2><div class="log" id="log"></div></aside></main><footer class="footer">Ziel: Erobere alle gegnerischen Gebäude. Nahrung begrenzt die Soldatenproduktion; Gold finanziert Upgrades; Wissen gewährt zufällige Forschung.</footer></div><div id="modal" class="modal hidden"><div class="modal-card"><h2>Forschung abgeschlossen</h2><p>Wähle genau eine Erweiterung:</p><div class="research" id="research"></div></div></div>`;
this.root.querySelectorAll('[data-send]').forEach(b=>b.onclick=()=>this.beginAttack(+b.dataset.send));this.root.querySelector('#pause').onclick=()=>this.paused=!this.paused;this.root.querySelector('#save').onclick=()=>this.save();this.root.querySelector('#load').onclick=()=>this.load();this.root.querySelector('#upgrade').onclick=()=>this.upgrade();}
tick(dt){if(this.paused||this.gameOver)return;this.elapsed+=dt;this.lastAI+=dt;if(this.elapsed>=CONFIG.seasonSeconds){this.elapsed=0;this.seasonIndex=(this.seasonIndex+1)%SEASONS.length;this.log('Jahreszeit: '+SEASONS[this.seasonIndex].name);}this.produce(dt);this.moveArmies(dt);if(this.lastAI>=CONFIG.aiIntervalSeconds){this.lastAI=0;this.aiMove();}if(this.knowledge>=CONFIG.researchThreshold)this.offerResearch();this.checkWin();this.render();}
produce(dt){const s=SEASONS[this.seasonIndex];let playerSoldiers=0;for(const n of this.nodes){if(n.owner!=='player'&&n.owner!=='enemy')continue;if(n.type==='castle'){const foodAvailable=n.owner==='enemy'||this.food>0;if(foodAvailable){let rate=BUILDINGS.castle.rate*s.castle*(n.owner==='player'?this.mods.castleRate:1)*n.level;const cap=BUILDINGS.castle.capacity+10*(n.level-1);const gain=Math.min(rate*dt,cap-n.value);n.value+=gain;if(n.owner==='player')this.food=Math.max(0,this.food-gain*.14*this.mods.foodUse);}if(n.owner==='player')playerSoldiers+=n.value;}
if(n.owner==='player'&&n.type==='farm'){const cap=BUILDINGS.farm.capacity+this.mods.farmCapacity+10*(n.level-1);this.food=Math.min(cap*this.countOwned('farm'),this.food+BUILDINGS.farm.rate*s.farm*this.mods.farmRate*n.level*dt);}
if(n.owner==='player'&&n.type==='mine'){const cap=BUILDINGS.mine.capacity+this.mods.mineCapacity+5*(n.level-1);this.gold=Math.min(cap*this.countOwned('mine'),this.gold+BUILDINGS.mine.rate*s.mine*this.mods.mineRate*n.level*dt);}
if(n.owner==='player'&&n.type==='academy')this.knowledge+=BUILDINGS.academy.rate*s.academy*this.mods.academyRate*n.level*dt;}}
countOwned(type){return Math.max(1,this.nodes.filter(n=>n.owner==='player'&&n.type===type).length)}
select(id){const node=this.nodes.find(n=>n.id===id);if(!node)return;if(this.selected&&this.selected!==id&&this.nodes.find(n=>n.id===this.selected).owner==='player'){this.target=id;this.log('Ziel gewählt: '+BUILDINGS[node.type].name+'. Wähle Truppenanteil.');}else{this.selected=id;this.target=null;}this.render();}
beginAttack(frac){if(!this.selected||!this.target)return this.log('Erst eigene Burg, dann Ziel wählen.');const from=this.nodes.find(n=>n.id===this.selected),to=this.nodes.find(n=>n.id===this.target);if(from.owner!=='player'||from.type!=='castle')return this.log('Angriffe starten nur aus eigenen Burgen.');if(!this.connected(from.id,to.id))return this.log('Diese Gebäude sind nicht direkt verbunden.');const count=Math.floor(from.value*frac);if(count<1)return;from.value-=count;this.armies.push({owner:'player',from:from.id,to:to.id,count,progress:0,duration:CONFIG.attackTravelSeconds*this.mods.travel});this.log(`${count} Soldaten marschieren.`);this.selected=null;this.target=null;}
connected(a,b){return this.routes.some(r=>r.includes(a)&&r.includes(b))}
moveArmies(dt){for(const a of this.armies)a.progress+=dt/a.duration;const arrived=this.armies.filter(a=>a.progress>=1);this.armies=this.armies.filter(a=>a.progress<1);arrived.forEach(a=>this.resolve(a));}
resolve(a){const t=this.nodes.find(n=>n.id===a.to);if(t.owner===a.owner){t.value+=a.count;return;}const defense=t.owner==='player'?this.mods.defense:1;const attack=a.count;const defended=t.value*defense;if(attack>defended){t.owner=a.owner;t.value=(attack-defended)/defense;this.log(`${BUILDINGS[t.type].name} wurde von ${a.owner==='player'?'dir':'der KI'} erobert.`);}else{t.value=Math.max(0,(defended-attack)/defense);this.log(`Angriff auf ${BUILDINGS[t.type].name} abgewehrt.`);}}
aiMove(){const castles=this.nodes.filter(n=>n.owner==='enemy'&&n.type==='castle'&&n.value>=8);if(!castles.length)return;const from=castles.sort((a,b)=>b.value-a.value)[0];const targets=this.nodes.filter(n=>n.id!==from.id&&this.connected(from.id,n.id)&&n.owner!=='enemy');if(!targets.length)return;const to=targets.sort((a,b)=>a.value-b.value)[0];const count=Math.floor(from.value*.5);from.value-=count;this.armies.push({owner:'enemy',from:from.id,to:to.id,count,progress:0,duration:CONFIG.attackTravelSeconds*1.1});this.log(`Feindliche Armee (${count}) ist unterwegs.`);}
upgrade(){if(!this.selected)return this.log('Wähle ein eigenes Gebäude.');const n=this.nodes.find(n=>n.id===this.selected);if(n.owner!=='player')return;if(this.gold<15)return this.log('Nicht genug Gold.');this.gold-=15;n.level++;this.log(`${BUILDINGS[n.type].name} auf Stufe ${n.level} verbessert.`);}
offerResearch(){this.paused=true;this.knowledge-=CONFIG.researchThreshold;const opts=[...RESEARCH].sort(()=>Math.random()-.5).slice(0,3);const modal=this.root.querySelector('#modal'),box=this.root.querySelector('#research');box.innerHTML='';opts.forEach(r=>{const b=document.createElement('button');b.innerHTML=`<b>${r.name}</b><br><small>${r.desc}</small>`;b.onclick=()=>{r.apply(this);this.log('Forschung: '+r.name);modal.classList.add('hidden');this.paused=false;};box.appendChild(b)});modal.classList.remove('hidden');}
checkWin(){const enemies=this.nodes.some(n=>n.owner==='enemy');const player=this.nodes.some(n=>n.owner==='player');if(!enemies){this.gameOver=true;this.log('SIEG – alle feindlichen Bastionen wurden erobert.');alert('Sieg!');}else if(!player){this.gameOver=true;alert('Niederlage.');}}
render(){this.root.querySelector('#food').textContent=this.food.toFixed(1);this.root.querySelector('#gold').textContent=this.gold.toFixed(1);this.root.querySelector('#knowledge').textContent=this.knowledge.toFixed(1)+' / '+CONFIG.researchThreshold;this.root.querySelector('#season').textContent=SEASONS[this.seasonIndex].name+' · '+Math.ceil(CONFIG.seasonSeconds-this.elapsed)+'s';const map=this.root.querySelector('#map');map.innerHTML='';for(const [a,b] of this.routes){const A=this.nodes.find(n=>n.id===a),B=this.nodes.find(n=>n.id===b);const x1=A.x,y1=A.y,x2=B.x,y2=B.y,dx=x2-x1,dy=y2-y1,len=Math.hypot(dx,dy),ang=Math.atan2(dy,dx)*180/Math.PI;const r=document.createElement('div');r.className='route';r.style.cssText=`left:${x1}%;top:${y1}%;width:${len}%;transform:rotate(${ang}deg)`;map.appendChild(r)}for(const n of this.nodes){const e=document.createElement('div');e.className=`node ${n.owner} ${this.selected===n.id||this.target===n.id?'selected':''}`;e.style.left=`calc(${n.x}% - 56px)`;e.style.top=`calc(${n.y}% - 56px)`;e.innerHTML=`<div>${BUILDINGS[n.type].icon}</div><div class="type">${BUILDINGS[n.type].name} · L${n.level}</div><div class="value">${Math.floor(n.value)}</div><div class="small">${n.owner==='player'?'Du':n.owner==='enemy'?'Gegner':'Neutral'}</div>`;e.onclick=()=>this.select(n.id);map.appendChild(e)}for(const a of this.armies){const A=this.nodes.find(n=>n.id===a.from),B=this.nodes.find(n=>n.id===a.to);const e=document.createElement('div');e.className='army '+(a.owner==='enemy'?'enemy':'');e.textContent=a.count;e.style.left=`calc(${A.x+(B.x-A.x)*a.progress}% - 12px)`;e.style.top=`calc(${A.y+(B.y-A.y)*a.progress}% - 12px)`;map.appendChild(e)}this.root.querySelector('#log').innerHTML=this.logs.slice(-40).reverse().map(x=>`<div>${x}</div>`).join('');}
log(x){this.logs.push(new Date().toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit',second:'2-digit'})+' · '+x);if(this.root.querySelector('#log'))this.render();}
save(){localStorage.setItem('bastion-stage1',JSON.stringify({nodes:this.nodes,food:this.food,gold:this.gold,knowledge:this.knowledge,mods:this.mods,seasonIndex:this.seasonIndex}));this.log('Spielstand gespeichert.');}
load(){const x=localStorage.getItem('bastion-stage1');if(!x)return this.log('Kein Spielstand vorhanden.');Object.assign(this,JSON.parse(x));this.armies=[];this.log('Spielstand geladen.');this.render();}}
